export const CURRENT_USER = {
  id: 'u1',
  name: 'Priya Anand',
  handle: '@priyareads',
  initials: 'PA',
  ink: 12300,
  lens: 'empath',
  bio: 'I read with my whole nervous system. Tamil-American writer exploring grief, inheritance, and the grammar of memory.',
  location: 'Brooklyn, NY',
  joined: 'Jan 2026',
  isFoundingReader: true,
  streak: { current: 47, best: 47 },
  stats: { posts: 34, followers: 892, following: 214, books: 11 },
  currentlyReading: { title: 'Beloved', author: 'Toni Morrison', progress: 68 },
};

export const BOOKS = [
  { id: 'bk1', title: 'Beloved', author: 'Toni Morrison', year: 1987, pages: 324, coverColor: '#8B4513', genre: 'Literary Fiction', rating: 4.8, reviews: 47, trending: true },
  { id: 'bk2', title: 'The God of Small Things', author: 'Arundhati Roy', year: 1997, pages: 340, coverColor: '#2A7C7C', genre: 'Literary Fiction', rating: 4.7, reviews: 31, trending: true },
  { id: 'bk3', title: 'Intermezzo', author: 'Sally Rooney', year: 2024, pages: 448, coverColor: '#5B9BD5', genre: 'Contemporary', rating: 4.2, reviews: 89, trending: true },
  { id: 'bk4', title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', year: 1967, pages: 417, coverColor: '#D4A030', genre: 'Magical Realism', rating: 4.9, reviews: 56, trending: false },
  { id: 'bk5', title: 'Kokoro', author: 'Natsume Sōseki', year: 1914, pages: 248, coverColor: '#9B7ED4', genre: 'Literary Fiction', rating: 4.5, reviews: 18, trending: false },
  { id: 'bk6', title: 'Things Fall Apart', author: 'Chinua Achebe', year: 1958, pages: 209, coverColor: '#4A7A4A', genre: 'Literary Fiction', rating: 4.6, reviews: 42, trending: false },
  { id: 'bk7', title: 'Song of Solomon', author: 'Toni Morrison', year: 1977, pages: 337, coverColor: '#6B3A6B', genre: 'Literary Fiction', rating: 4.7, reviews: 29, trending: false },
  { id: 'bk8', title: 'Persepolis', author: 'Marjane Satrapi', year: 2000, pages: 153, coverColor: '#C45B4A', genre: 'Graphic Memoir', rating: 4.8, reviews: 34, trending: false },
  { id: 'bk9', title: 'Convenience Store Woman', author: 'Sayaka Murata', year: 2016, pages: 163, coverColor: '#8BAAB8', genre: 'Contemporary', rating: 4.4, reviews: 61, trending: true },
  { id: 'bk10', title: 'The Stranger', author: 'Albert Camus', year: 1942, pages: 123, coverColor: '#7A7067', genre: 'Existential', rating: 4.3, reviews: 73, trending: false },
  { id: 'bk11', title: 'Normal People', author: 'Sally Rooney', year: 2018, pages: 273, coverColor: '#D06070', genre: 'Contemporary', rating: 4.1, reviews: 102, trending: false },
  { id: 'bk12', title: 'The Bell Jar', author: 'Sylvia Plath', year: 1963, pages: 234, coverColor: '#607090', genre: 'Literary Fiction', rating: 4.5, reviews: 88, trending: false },
];

export const POSTS = [
  {
    id: 'p1',
    type: 'original',
    author: { id: 'u1', name: 'Priya Anand', handle: '@priyareads', initials: 'PA', ink: 12300, lens: 'empath' },
    timeAgo: '2h',
    title: 'Inheritance Tax',
    text: 'My grandmother left me her tongue.\n\nNot the language — I already had that, the Tamil she\'d fed me like rice water when I was small. No. She left me the physical fact of her voice. The way it dropped to a whisper when she was furious. The way it climbed when she was lying.\n\nI discovered this at her funeral, when I opened my mouth to read the eulogy and my mother grabbed my arm.\n\n"You sound exactly like her," she said.\n\nShe did not mean it as a comfort.',
    likes: 489, comments: 124, shelved: 183, reposts: 72,
    tags: ['Personal Essay', 'Tender', 'Haunting'],
    attested: true,
  },
  {
    id: 'p2',
    type: 'review',
    author: { id: 'u2', name: 'Kofi Asante', handle: '@kofi_writes', initials: 'KA', ink: 8750, lens: 'storyteller' },
    timeAgo: '4h',
    bookRef: { title: 'Beloved', author: 'Toni Morrison' },
    text: 'Morrison doesn\'t write sentences. She builds rooms you have to live in. Beloved is a house — 124 Bluestone Road — and it breathes, rejects, remembers. By page 200 I understood that the ghost isn\'t a metaphor. She\'s the cost of survival made flesh.',
    likes: 178, comments: 96, shelved: 67, reposts: 22,
    tags: ['Literary Fiction', 'Visceral'],
    attested: false,
  },
  {
    id: 'p3',
    type: 'recommendation',
    author: { id: 'u3', name: 'Elena Vasquez', handle: '@elenavasquez', initials: 'EV', ink: 3200, lens: 'philosopher' },
    timeAgo: '6h',
    bookRef: { title: 'The God of Small Things', author: 'Arundhati Roy' },
    text: 'If you\'ve ever felt a language living inside your body rather than your mind — read this. Roy writes English the way my grandmother spoke Tamil: as if the words were made of something heavier and sweeter than sound.',
    likes: 267, comments: 58, shelved: 201, reposts: 44,
    tags: ['Literary Fiction', 'Luminous'],
    attested: false,
  },
  {
    id: 'p4',
    type: 'original',
    author: { id: 'u4', name: 'James Huang', handle: '@jamesreads', initials: 'JH', ink: 1840, lens: 'analyst' },
    timeAgo: '8h',
    title: 'The Cartographer\'s Confession',
    text: 'The first map I ever drew was a lie.\n\nI was nine, and my father had asked me to sketch the walk from our house to the schoolyard. I drew it faithfully — the cracked sidewalk past Miss Lorraine\'s porch, the shortcut through the empty lot where glass glittered in the dirt like fallen stars.\n\nBut when I reached the schoolyard itself, I kept drawing.',
    likes: 312, comments: 87, shelved: 94, reposts: 41,
    tags: ['Literary Fiction', 'Quiet', 'Meditative'],
    attested: false,
  },
  {
    id: 'p5',
    type: 'spoiler',
    author: { id: 'u2', name: 'Kofi Asante', handle: '@kofi_writes', initials: 'KA', ink: 8750, lens: 'storyteller' },
    timeAgo: '12h',
    bookRef: { title: 'Intermezzo', author: 'Sally Rooney' },
    text: 'Peter\'s breakdown in chapter 28 mirrors Connell\'s in Normal People almost beat for beat — but where Connell collapses inward, Peter\'s collapse is performative. Rooney is doing something really specific about how men perform emotional crisis for the women who love them.',
    likes: 145, comments: 203, shelved: 38, reposts: 19,
    tags: ['Contemporary', 'Sharp'],
    attested: false,
    spoilerPage: 280,
  },
  {
    id: 'p6',
    type: 'review',
    author: { id: 'u5', name: 'Nneka Obi', handle: '@nneka_reads', initials: 'NO', ink: 560, lens: 'empath' },
    timeAgo: '1d',
    bookRef: { title: 'Things Fall Apart', author: 'Chinua Achebe' },
    text: 'Okonkwo is not a villain. He\'s a man who confused strength with silence and paid the only price that mattered. Achebe gives him tragedy without sympathy — the rarest, hardest gift a writer can give a character.',
    likes: 334, comments: 112, shelved: 147, reposts: 56,
    tags: ['Literary Fiction', 'Visceral', 'Dark'],
    attested: false,
  },
  {
    id: 'p7',
    type: 'original',
    author: { id: 'u3', name: 'Elena Vasquez', handle: '@elenavasquez', initials: 'EV', ink: 3200, lens: 'philosopher' },
    timeAgo: '1d',
    title: 'What the River Remembers',
    text: 'Every river has two memories: the one it carries and the one it leaves behind. The Ganges remembers every body it has taken. The Mississippi remembers every body it has hidden.\n\nWe name rivers as if they belong to places. But rivers are time itself — moving, carrying, arriving somewhere that is always the same and always changed.',
    likes: 198, comments: 43, shelved: 87, reposts: 31,
    tags: ['Personal Essay', 'Meditative', 'Luminous'],
    attested: true,
  },
];

export const NOTIFICATIONS = [
  { id: 'n1', type: 'like', actor: { name: 'Kofi Asante', initials: 'KA', ink: 8750 }, postTitle: 'Inheritance Tax', timeAgo: '2m', read: false },
  { id: 'n2', type: 'comment', actor: { name: 'Elena Vasquez', initials: 'EV', ink: 3200 }, postTitle: 'Inheritance Tax', preview: 'This line about the tongue — I felt it physically.', timeAgo: '15m', read: false },
  { id: 'n3', type: 'shelf', actor: { name: 'James Huang', initials: 'JH', ink: 1840 }, postTitle: 'Inheritance Tax', shelfName: 'Writing That Cuts', timeAgo: '1h', read: false },
  { id: 'n4', type: 'follow', actor: { name: 'Nneka Obi', initials: 'NO', ink: 560 }, timeAgo: '2h', read: true },
  { id: 'n5', type: 'ink', amount: 150, reason: 'Your post "Inheritance Tax" earned community engagement', timeAgo: '2h', read: true },
  { id: 'n6', type: 'repost', actor: { name: 'Kofi Asante', initials: 'KA', ink: 8750 }, postTitle: 'The Tongue My Grandmother Left Me', timeAgo: '5h', read: true },
  { id: 'n7', type: 'comment', actor: { name: 'James Huang', initials: 'JH', ink: 1840 }, postTitle: 'Inheritance Tax', preview: 'The detail about your mother\'s tone — devastating.', timeAgo: '6h', read: true },
  { id: 'n8', type: 'waypoint', actor: { name: 'Elena Vasquez', initials: 'EV', ink: 3200 }, bookTitle: 'Beloved', page: 184, timeAgo: '8h', read: true },
];

export const CONVERSATIONS = [
  {
    id: 'c1',
    with: { name: 'Kofi Asante', handle: '@kofi_writes', initials: 'KA', ink: 8750, online: true },
    lastMessage: { text: 'That ending though — did you expect it?', timeAgo: '5m', mine: false },
    unread: 2,
    messages: [
      { id: 'm1', mine: false, text: 'Just finished The God of Small Things. You were right about everything.', timeAgo: '1h' },
      { id: 'm2', mine: true, text: 'I told you! The language alone is worth it.', timeAgo: '58m' },
      { id: 'm3', mine: false, text: 'The way she writes caste — it\'s architectural. You feel it as structure.', timeAgo: '45m' },
      { id: 'm4', mine: true, text: 'Yes! The "Love Laws" as literal laws governing space. Roy is building the prison of the novel around you before you realize you\'re inside it.', timeAgo: '40m' },
      { id: 'm5', mine: false, text: 'That ending though — did you expect it?', timeAgo: '5m' },
    ],
  },
  {
    id: 'c2',
    with: { name: 'Elena Vasquez', handle: '@elenavasquez', initials: 'EV', ink: 3200, online: false },
    lastMessage: { text: 'Reading your "Inheritance Tax" piece changed how I think about translation.', timeAgo: '2h', mine: false },
    unread: 0,
    messages: [
      { id: 'm6', mine: false, text: 'Reading your "Inheritance Tax" piece changed how I think about translation.', timeAgo: '2h' },
      { id: 'm7', mine: true, text: 'That means a lot — I wasn\'t sure it landed.', timeAgo: '1h' },
    ],
  },
  {
    id: 'c3',
    with: { name: 'James Huang', handle: '@jamesreads', initials: 'JH', ink: 1840, online: false },
    lastMessage: { text: 'Want to co-write something for The Press?', timeAgo: '1d', mine: false },
    unread: 1,
    messages: [
      { id: 'm8', mine: false, text: 'Your Toni Morrison shelf is incredible — have you read Song of Solomon?', timeAgo: '2d' },
      { id: 'm9', mine: true, text: 'Yes! It\'s on my shelf. Sula is the one that broke me though.', timeAgo: '2d' },
      { id: 'm10', mine: false, text: 'Want to co-write something for The Press?', timeAgo: '1d' },
    ],
  },
];

export const SHELVES = [
  {
    id: 's1', name: 'Stories That Wrecked Me',
    desc: 'Fiction that left a mark I couldn\'t wash off.',
    count: 7, followers: 234,
    books: ['Inheritance Tax', 'The Cartographer\'s Confession', 'Grief Manual', 'Mother Tongues', 'Unsent Letters', 'Beloved', 'The God of Small Things'],
    curator: { name: 'Priya Anand', initials: 'PA', ink: 12300 },
  },
  {
    id: 's2', name: 'The Grief Library',
    desc: 'Everything I\'ve read about loss, and what stayed.',
    count: 5, followers: 178,
    books: ['Beloved', 'Year of Magical Thinking', 'Blue Nights', 'Ocean at End of Lane', 'Smoke Gets in Eyes'],
    curator: { name: 'Priya Anand', initials: 'PA', ink: 12300 },
  },
  {
    id: 's3', name: 'Writers to Watch',
    desc: 'First-time authors on Précis who stopped me mid-scroll.',
    count: 4, followers: 312,
    books: ['Nneka\'s Debut', 'Tomás Rivera', 'James Huang', 'Lila Okonkwo'],
    curator: { name: 'Priya Anand', initials: 'PA', ink: 12300 },
  },
  {
    id: 's4', name: 'Before You Read Beloved',
    desc: 'Context, companion reads, and the essays that make Morrison hit harder.',
    count: 3, followers: 89,
    books: ['Song of Solomon', 'Sula', 'The Origin of Others'],
    curator: { name: 'Priya Anand', initials: 'PA', ink: 12300 },
  },
];

export const CHALLENGES = [
  {
    id: 'ch1',
    title: 'Read the World',
    desc: 'One book from each inhabited continent in 2026.',
    progress: 4, total: 7, participants: 1247,
    deadline: 'Dec 31, 2026',
    tags: ['Global', 'Annual'],
    joined: true,
    books: [
      { title: 'Things Fall Apart', author: 'Chinua Achebe', region: 'Africa', done: true },
      { title: 'The God of Small Things', author: 'Arundhati Roy', region: 'Asia', done: true },
      { title: 'Beloved', author: 'Toni Morrison', region: 'North America', done: true },
      { title: 'One Hundred Years of Solitude', author: 'García Márquez', region: 'South America', done: true },
      { title: 'TBD', author: '', region: 'Europe', done: false },
      { title: 'TBD', author: '', region: 'Oceania', done: false },
      { title: 'TBD', author: '', region: 'Antarctica (essay)', done: false },
    ],
  },
  {
    id: 'ch2',
    title: 'Toni Morrison Complete',
    desc: 'Read all eleven novels. Chronological order recommended.',
    progress: 3, total: 11, participants: 432,
    deadline: 'No deadline',
    tags: ['Author', 'Completionist'],
    joined: true,
    books: [
      { title: 'The Bluest Eye', author: 'Toni Morrison', year: 1970, done: true },
      { title: 'Sula', author: 'Toni Morrison', year: 1973, done: true },
      { title: 'Song of Solomon', author: 'Toni Morrison', year: 1977, done: true },
      { title: 'Tar Baby', author: 'Toni Morrison', year: 1981, done: false },
      { title: 'Beloved', author: 'Toni Morrison', year: 1987, done: false },
      { title: 'Jazz', author: 'Toni Morrison', year: 1992, done: false },
    ],
  },
  {
    id: 'ch3',
    title: 'March Reading Sprint',
    desc: 'Read 4 books in March. Any genre, any length.',
    progress: 2, total: 4, participants: 3891,
    deadline: 'Mar 31, 2026',
    tags: ['Monthly', 'Sprint'],
    joined: false,
  },
  {
    id: 'ch4',
    title: 'Translated in Translation',
    desc: 'Six books originally written in non-English languages.',
    progress: 0, total: 6, participants: 872,
    deadline: 'Jun 30, 2026',
    tags: ['Translation', 'Global'],
    joined: false,
  },
];

export const CLUBS = [
  {
    id: 'cl1',
    name: 'The Grief Readers',
    desc: 'A space for reading and discussing literature about loss, mourning, and survival.',
    members: 47, currentBook: { title: 'Beloved', author: 'Toni Morrison' },
    chapter: 'Part Two, Chapters 18–22',
    nextMeeting: 'Mar 28, 2026', joined: true,
    tags: ['Literary Fiction', 'Grief'],
    admin: { name: 'Priya Anand', initials: 'PA' },
  },
  {
    id: 'cl2',
    name: 'Contemporary Voices',
    desc: 'New releases and debut fiction from under-represented writers.',
    members: 128, currentBook: { title: 'Intermezzo', author: 'Sally Rooney' },
    chapter: 'Chapters 12–18',
    nextMeeting: 'Mar 30, 2026', joined: true,
    tags: ['Contemporary', 'New Releases'],
    admin: { name: 'Kofi Asante', initials: 'KA' },
  },
  {
    id: 'cl3',
    name: 'World Literature Circle',
    desc: 'Books from every corner of the globe. One continent per month.',
    members: 234, currentBook: { title: 'Kokoro', author: 'Natsume Sōseki' },
    chapter: 'Part II: My Parents and I',
    nextMeeting: 'Apr 5, 2026', joined: false,
    tags: ['Global', 'Translated'],
    admin: { name: 'Elena Vasquez', initials: 'EV' },
  },
  {
    id: 'cl4',
    name: 'The Essay Room',
    desc: 'Personal essays, literary criticism, and long-form nonfiction.',
    members: 89, currentBook: { title: 'The Origin of Others', author: 'Toni Morrison' },
    chapter: 'Chapters 1–3',
    nextMeeting: 'Apr 12, 2026', joined: false,
    tags: ['Nonfiction', 'Essays'],
    admin: { name: 'James Huang', initials: 'JH' },
  },
];

export const PRESS_POSTS = [
  {
    id: 'pr1',
    type: 'original',
    featured: true,
    editorPick: true,
    author: { name: 'Priya Anand', handle: '@priyareads', initials: 'PA', ink: 12300, lens: 'empath' },
    title: 'Inheritance Tax',
    excerpt: 'My grandmother left me her tongue. Not the language — I already had that, the Tamil she\'d fed me like rice water when I was small...',
    timeAgo: '2d',
    likes: 489, comments: 124, shelved: 183,
    tags: ['Personal Essay', 'Tender', 'Haunting'],
    readTime: '4 min',
  },
  {
    id: 'pr2',
    type: 'original',
    featured: false,
    editorPick: false,
    author: { name: 'Kofi Asante', handle: '@kofi_writes', initials: 'KA', ink: 8750, lens: 'storyteller' },
    title: 'The Cartographer\'s Confession',
    excerpt: 'The first map I ever drew was a lie. I was nine, and my father had asked me to sketch the walk from our house to the schoolyard...',
    timeAgo: '5d',
    likes: 312, comments: 87, shelved: 94,
    tags: ['Literary Fiction', 'Quiet'],
    readTime: '6 min',
  },
  {
    id: 'pr3',
    type: 'original',
    featured: false,
    editorPick: true,
    author: { name: 'Elena Vasquez', handle: '@elenavasquez', initials: 'EV', ink: 3200, lens: 'philosopher' },
    title: 'What the River Remembers',
    excerpt: 'Every river has two memories: the one it carries and the one it leaves behind. The Ganges remembers every body it has taken...',
    timeAgo: '1d',
    likes: 198, comments: 43, shelved: 87,
    tags: ['Personal Essay', 'Meditative'],
    readTime: '3 min',
  },
  {
    id: 'pr4',
    type: 'original',
    featured: false,
    editorPick: false,
    author: { name: 'James Huang', handle: '@jamesreads', initials: 'JH', ink: 1840, lens: 'analyst' },
    title: 'On Sentences That Know They\'re Being Watched',
    excerpt: 'Some writers perform for the reader. Others perform for the sentence. Sally Rooney belongs to the second category...',
    timeAgo: '3d',
    likes: 156, comments: 39, shelved: 72,
    tags: ['Cultural Criticism', 'Sharp'],
    readTime: '5 min',
  },
];

export const EXPLORE_READERS = [
  { id: 'u2', name: 'Kofi Asante', handle: '@kofi_writes', initials: 'KA', ink: 8750, lens: 'storyteller', currentlyReading: 'The God of Small Things', followers: 1240 },
  { id: 'u3', name: 'Elena Vasquez', handle: '@elenavasquez', initials: 'EV', ink: 3200, lens: 'philosopher', currentlyReading: 'Kokoro', followers: 678 },
  { id: 'u4', name: 'James Huang', handle: '@jamesreads', initials: 'JH', ink: 1840, lens: 'analyst', currentlyReading: 'Intermezzo', followers: 445 },
  { id: 'u5', name: 'Nneka Obi', handle: '@nneka_reads', initials: 'NO', ink: 560, lens: 'empath', currentlyReading: 'Beloved', followers: 223 },
];
